language: node_js  #设置语言

node_js: stable  #设置相应的版本

before_install:
  - export TZ=Asia/Shanghai #设置build环境所采用的时区

install:
  - npm install  #安装hexo及插件

before_script:
  - git config --global user.name "suchenrain"
  - git config --global user.email "suchenxiaoyu@gmail.com"
  - sed -i "s/__Baidu_Push_Token__/${Baidu_Push_Token}/" _config.yml
  - sed -i "s/__GH_Token__/${GH_Token}/" _config.yml

script: npm run build
  # - hexo cl  #清除
  # - hexo g  #生成
  # - hexo deploy #发布


# after_script:
#   - cd ./public
#   - git init
#   - git config user.name "suchenrain"  #修改name
#   - git config user.email "suchenxiaoyu@gmail.com"  #修改email
#   - git add .
#   - git commit -m "update"
#   - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - hexo  #只监测hexo分支
env:
 global:
   - GH_REF: github.com/suchenrain/suchenrain.github.io.git  #设置GH_REF